### ISSUE TITLE
How to install bcmath

### ISSUE THREAD

**Issue by dlopez** [geerlingguy/drupal-for-kubernetes#42]
bcmath is required for Drupal commerce. I tried to add `RUN docker-php-ext-install bcmath` but docker-php-ext-install is not found.

**Comment by geerlingguy** [comment]
This image is based on geerlingguy/drupal (see https://github.com/geerlingguy/drupal-for-kubernetes/blob/master/Dockerfile), and that in turn is based on my php-apache-container, which is not set up in a way that is as flexible as the base PHP container image (mostly because I needed to do some tweaks to get it to run well on ARM) — see https://github.com/geerlingguy/php-apache-container

You'd need to build in the support manually in your own Dockerfile or rebuild the base php-apache-container then the docker container on top of it, and finally this container.

**Comment by dlopez** [comment]
Thank you!
